from __future__ import annotations

ASSET_STATUS_PENDING = "pending"
ASSET_STATUS_UPLOADED = "uploaded"
ASSET_STATUS_PROCESSING = "processing"
ASSET_STATUS_READY = "ready"
ASSET_STATUS_FAILED = "failed"
ASSET_STATUS_DELETED = "deleted"
ASSET_STATUS_INDEXING = "indexing"

INDEX_JOB_STATUS_QUEUED = "queued"
INDEX_JOB_STATUS_RUNNING = "running"
INDEX_JOB_STATUS_DONE = "done"
INDEX_JOB_STATUS_FAILED = "failed"

RESOURCE_TYPE_DOC = "doc"
RESOURCE_TYPE_AUDIO = "audio"
RESOURCE_TYPE_IMAGE = "image"
RESOURCE_TYPE_VIDEO = "video"

ALLOWED_RESOURCE_TYPES = {RESOURCE_TYPE_DOC, RESOURCE_TYPE_AUDIO, RESOURCE_TYPE_IMAGE, RESOURCE_TYPE_VIDEO}

JOB_KIND_INGEST = "ingest"
JOB_STATUS_QUEUED = "queued"
JOB_STATUS_RUNNING = "running"
JOB_STATUS_DONE = "done"
JOB_STATUS_FAILED = "failed"